### ISSUE TITLE
Installation issues - bamsignals

### ISSUE THREAD

**Issue by venuthatikonda** [lamortenera/bamsignals#18]
Hi,

I have been trying to install `bamsignals` package. When I install through `biocLite()`, it is giving the following error.

```
Error in system.file("lib", package = "Rhtslib", mustWork = TRUE) : 
  no file found
Calls: <Anonymous> -> system.file
Execution halted
```

But I already installed `Rhtslib`. It would be great if you could help me fixing this.

Thank you.

**Comment by lamortenera** [comment]
Hi venuthatikonda,
that's odd, the build reports show that everything should be fine: http://bioconductor.org/checkResults/release/bioc-LATEST/bamsignals/

Which R version are you using?
are you using the latest version of `bioconductor`?
Try to do:

    source("https://bioconductor.org/biocLite.R")
    biocLite()

Cheers
Alessandro

**Comment by venuthatikonda** [comment]
I am using the following versions. I think 3.4 is the latest Bioconductor version.

**R - 3.3.1 (2016-06-21) -- "Bug in Your Hair"**

**Bioconductor version 3.4.**

I've updated everything but still facing the error. 

Could you think of any reasons for this error?

**Comment by your-highness** [comment]
Is this issue fixed now?

**Comment by lamortenera** [comment]
HI Johannes,

are you having the same issue?
I didn't manage to reproduce it.

Cheers
Alessandro

**Comment by your-highness** [comment]
No, I just wanted to know otherwise you could close that issue...

**Comment by venuthatikonda** [comment]
No, it is not fixed. But you can close it.
