### ISSUE TITLE
Accounting for fragment length

### ISSUE THREAD

**Issue by yancychy** [lamortenera/bamsignals#21]
Hi , I find the document in 
https://bioconductor.org/packages/release/bioc/vignettes/bamsignals/inst/doc/bamsignals.html .
My question is about shift process in bamCount to extract reads count from given intervals.
In my understanding, the shift process should be as follows: 
1. Shift all reads in the bam based shift size 2. Counts the reads number in the intervals. 

But I also guess that your shift process may be:
1. For each interval, shift the reads only in the interval. 2. Count the reads number in the intervals. 

I am not sure which one is the right for the your process. 

Thanks very much. 

Best regards,
Yang

**Comment by your-highness** [comment]
Dear @yancychy

I don't exactly see your question here. See 1.2.2. in the vignette for a clarification on how the shift is done:

> 1.2.2 Accounting for fragment length
> With the `bamCount()` function a read is counted in a range if the 5’ end of the read falls in that range. This might be appropriate when analyzing DNase I hypersensitivity tags, however for ChIP-seq data the immunoprecipitated protein is normally located downstream with respect to the 5’ end of the sequenced reads. **To correct for that, it is possible to count reads with a strand-specific shift, i.e. reads will be counted in a range if the shifted 5’ end falls in that range.** Note that this shift will move reads mapped to the positive strand to the right and reads mapped to the negative strand to the left with respect to the reference orientation. The shift should correspond approximately to half of the average length of the fragments in the sequencing experiment.

Also the shift is done on the level of the single nt-resolution count vector and later collapsed into given ranges.

_Does this clarify our approach for shifting read ends?_

Best,

**Comment by yancychy** [comment]
Yes, Thanks for your clear explaination. The reads will be shifted first and then counted in the given ranges. 
Best regard
Yang

**Comment by your-highness** [comment]
Correct
