### ISSUE TITLE
build problems on Windows

### ISSUE THREAD

**Issue by lamortenera** [lamortenera/bamsignals#8]
Nate says that there are problems building bamsignals on Windows

**Comment by nhayden** [comment]
[Link to the latest Windows build report](http://bioconductor.org/checkResults/devel/bioc-LATEST/bamsignals/moscato2-checksrc.html).

This appears to be fixed via f62ceedc8ac9af9cdd8a894d616548466b6b63b0.

The error was that loading an index file (calling [`bam_index_load(cbampath)`](https://github.com/lamortenera/bamsignals/blob/5a688ef8975729f5c9baae4cdb8acd66991a0d59/src/bamsignals.cpp#L206)) during unit tests returned `0` when called on a BAM file written with [`writeSamAsBamAndIndex`](https://github.com/lamortenera/bamsignals/blob/5a688ef8975729f5c9baae4cdb8acd66991a0d59/src/bamsignals.cpp#L479) despite the fact the BAM file had a corresponding `.bai` index file written by `writeSamAsBamAndIndex`. Presumably the error was a parse error.

The problem did not occur if I limited the number of iterations of the [`bam_write1`](https://github.com/lamortenera/bamsignals/blob/5a688ef8975729f5c9baae4cdb8acd66991a0d59/src/bamsignals.cpp#L502) loop to a small number, e.g., 400.

Hooray unit tests!
